import './globals.css';
import type { Metadata } from 'next';
import React from "react";
import {AlertProvider} from "@/components/alert/AlertContext";
import {AlertContainer} from "@/components/alert/AlertContainer";

export const metadata: Metadata = {
    title: "Sand Alerts",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body>
        <AlertProvider>
            {children}
            <AlertContainer />
        </AlertProvider>
        </body>
        </html>
    );
}